version: "3.9"

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_PASSWORD_: password

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - clima

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      DB_NAME: database
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
    depends_on:
      - db
    networks:
      - clima

volumes:
  db_data:

networks:
  clima:
    driver: bridge