# Generated by Django 5.2.3 on 2025-06-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='agno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='mes',
            field=models.IntegerField(),
        ),
    ]
