# Generated by Django 5.2.3 on 2025-06-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_weather_agno_alter_weather_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='probabilidad',
            field=models.IntegerField(max_length=255),
        ),
    ]
