# Generated by Django 5.2.3 on 2025-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_weather_probabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='dia',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='probabilidad',
            field=models.IntegerField(),
        ),
    ]
